import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
export const metadata = {
  title: "Steven Junio",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body className="min-h-screen">
          <Theme>{children} </Theme>
          <SpeedInsights />
        </body>
      </UserProvider>
    </html>
  );
}
