services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: node:20.11.1-alpine3.19
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock