import Link from "next/link";
import "./globals.css";
import { headers } from "next/headers";
import path from "path";

export const metadata = {
  title: "Steven Junio",
  description: "Generated by Next.js",
};

const pathname = headers().get("referer") || "";
const currentPath = path.basename(pathname);

const navMenu = [
  {
    title: "Home",
    link: "/",
    active: currentPath === "home" ? true : false,
  },
  {
    title: "Blog",
    link: "/blog",
    active: currentPath === "blog" ? true : false,
  },
  {
    title: "Projects",
    link: "/projects",
    active: currentPath === "projects" ? true : false,
  },
  {
    title: "Contact",
    link: "/contact",
    active: currentPath === "contact" ? true : false,
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="sm:w-full sm:flex sm:flex-col sm:bg-slate-800 sm:py-4 text-white">
          <h1 className="text-3xl w-fit m-auto">Steven Junio</h1>
          <hr className="w-[calc(100%-40px)] m-auto my-2" />
          <nav className="" id="main-nav">
            <ul className="flex justify-center gap-4 text-xl">
              {navMenu.map((item) => (
                <li
                  className={
                    item.active
                      ? "bg-slate-600 p-2 rounded-md"
                      : "p-2 hover:bg-slate-900 rounded-md"
                  }
                  key={item.title}
                >
                  <Link href={item.link}>{item.title}</Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
