import "./globals.css";
import HideableHeader from "./components/HideableHeader";

export const metadata = {
  title: "Steven Junio",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <HideableHeader />
        {children}
      </body>
    </html>
  );
}
