import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Steven Junio',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="sm:w-full sm:flex sm:flex-col sm:bg-slate-800 sm:py-4">
          <h1 className="text-3xl w-fit m-auto">Steven Junio</h1>
          <hr className="w-[calc(100%-40px)] m-auto my-2" />
          <nav className='' id='main-nav'>
            <ul className='flex justify-center gap-4 text-xl'>
              <li><Link href={'/'}>Home</Link></li>
              <li>Blog</li>
              <li>Projects</li>
              <li>Contact</li>
            </ul>
          </nav>
          </header>
        {children}</body>
    </html>
  )
}
