name: test and deploy to prod
run-name: test and deploy to prod
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  merge-to-production:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run database schema migration
        run: |
          npx prisma migrate deploy
           echo "Database schema migration completed"
        env:
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
          name: Configure Git
          run: |
            git config user.name "GitHub Action"
            git config user.email "action@github.com"
      - name: Merge main into production
        run: |
          git fetch origin production:production
          git checkout production
          git merge --ff-only main
          git push origin production
